'use strict';

module.exports = function (/*app*/) {
  return {
    /////////////
    // GENERAL //
    /////////////
    API_VALIDATION_ERROR: 400,
    UPLOAD_ERROR: 401,
    UNKNOWN_ERROR: 402,
    N0_ACCESS: 403,
    IMAGE_NOT_FOUND: 404,

    ////////////
    // COMMON //
    ////////////
    INVALID_FILE_TYPE: 501,
    NO_USER_ACCESS: 502,

    //////////
    // AUTH //
    //////////
    SESSION_NOT_FOUND: 1000,
    OTP_INVALID: 1001,
    OTP_TIMEDOUT: 1002,
    PASSWORD_MISMATCH: 1003,
    SOCIAL_ID_NOT_FOUND: 1004,
    ACCESS_TOKEN_EXPIRED: 1005,
    REFRESH_TOKEN_EXPIRED: 1006,

    ////////////
    // ADMIN  //
    ////////////
    ADMIN_NOT_FOUND: 1100,
    ADMIN_HAS_BEEN_SUSPENDED: 1101,
    ADMIN_EMAIL_ALREADY_EXISTS: 1102,
    ADMIN_HAS_BEEN_DELETED: 1103,
    ADMIN_BLOCKED_BY_ADMIN: 1104,
    ROLE_ALREADY_EXISTS: 1105,
    ADMIN_ALREADY_EXISTS_FOR_THIS_ROLE: 1106,

    ///////////
    // USER //
    /////////
    USER_NOT_FOUND: 1200,
    USER_HAS_BEEN_SUSPENDED: 1201,
    USER_ALREADY_EXISTS: 1202,
    USER_HAS_BEEN_DELETED: 1203,
    USER_BLOCKED_BY_ADMIN: 1204,
    USER_BLOCKED: 1205,
    USER_IS_ALREADY_REGISTERED: 1206,
    USER_DELETED: 1207,
    USER_IS_SOCIAL_REGISTERED: 1208,
    USER_ALREADY_REGISTERED_DIFFERENT_SOCIAL_ACCOUNT: 1209,
    // LANGUAGE
    LANGUAGE_ALREADY_EXISTS: 1301,

    // CATEGORY
    CATEGORY_ALREADY_EXISTS: 1311,
    CATEGORY_NOT_FOUND: 1312,

    // CITY
    CITY_ALREADY_EXISTS: 1321,

    //STORY
    STORY_ALREADY_EXISTS: 1341,
    STORY_ALREADY_SAVED: 1342,

    //ROUTE
    ROUTE_ALREADY_EXISTS: 1361,
    ROUTE_ALREADY_SAVED: 1362,

    //FAQ
    FAQ_ALREADY_EXISTS: 1381,

    // ADVERTISEMENT
    ADVERTISEMENT_ALREADY_EXISTS: 1391,

    ///////////////////
    // GLOBAL CONFIG //
    ///////////////////
    GLOBAL_CONFIG_NOT_FOUND: 1400,

    ///////////////////
    // Location     //
    ///////////////////
    LOCATION_ALREADY_EXISTS: 1450,

    ////////////////////////
    // RESTAURANT OWNER  //
    ////////////////////////
    RESTAURANT_OWNER_NOT_FOUND: 1500,
    RESTAURANT_OWNER_HAS_BEEN_SUSPENDED: 1501,
    RESTAURANT_OWNER_EMAIL_ALREADY_EXISTS: 1502,
    RESTAURANT_OWNER_HAS_BEEN_DELETED: 1503,
    RESTAURANT_OWNER_BLOCKED_BY_ADMIN: 1504,
    ROLE_ALREADY_EXISTS: 1505,
    RESTAURANT_OWNER_ALREADY_EXISTS_FOR_THIS_ROLE: 1506,

    RESTAURANT_ALREADY_EXISTS: 1550,

    MENU_ALREADY_EXISTS: 1600,
    MENU_NOT_FOUND: 1601,
  };
};
